# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_deletemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Step',
        ),
        migrations.DeleteModel(
            name='DeleteModel',
        ),
    ]
